### ISSUE TITLE
Create a simple logistic regression model (baseline model)

### ISSUE THREAD

**Issue by MelinaGoula** [MIE479-2024/msf-capstone-crm#1]
- [ ] Include only 1 quarter of data to start with (Q4 - after Sep 1)
- [ ] Consider scaling and standardization methods
- [ ] Investigate feature selection methods
_______________________________________________________________________________________
Include the following variables:
- orig_rt
- orig_amt
- orig_trm
- ocltv
- num_bo
- dti
- CSCORE_B
- FTHB_FLG
- purpose
- PROP_TYPE
- NUM_UNIT
- occ_stat
-

**Comment by Zhang10001** [comment]
US House Price Index by 3-digit Zip code, From Federal Housing Finance Agency (FHFA), Quarterly data from 1995Q1 to 2024Q2, 
Available at https://www.fhfa.gov/data/hpi/datasets 
HPI Datasets -> Quarterly Data -> All-Transactions Indexes (Estimated using Sales Prices and Appraisal Data) -> ​Three-Digit ZIP Codes (Developmental Index; Not Seasonally Adjusted)
Detailed calculation of index number (i.e. compared to which baseline year) incorporated into the dataset to be determined
