### ISSUE TITLE
Acquisition Data Preprocessing

### ISSUE THREAD

**Issue by MelinaGoula** [MIE479-2024/msf-capstone-crm#3]
Write a python script or notebook to preprocess data
-  [ ] Create a prediction column `y`
    -    Group F_30, F_60, F_90, F_120, F_180 i.e. `deliquency = 1` if any of the dates are not NULL
- [ ] Apply encoding on categorical columns

**Comment by zhu2680** [comment]
Apply weight or smote to delinquency data
apply XGBoost and see the performance
